VDOEasy/Models/ErrorViewModel.cs
namespace VDOEasy.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VDOEasy/Models/HomeViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using VDOEasy.Data.Models;

namespace VDOEasy.Models
{
    public class HomeViewModel
    {
        public List<SelectListItem> Branches { get; set; }
        public List<MasMemberType> MemberTypes { get; set; }
        public List<MasMoviesType> MoviesTypes { get; set; }
        public MemberModalViewModel MemberModal { get; set; }
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? Birthdate { get; set; }
        public string Address { get; set; }
        public string IdcardNumber { get; set; }
        public int MemberTypeId { get; set; }
        public List<int> UserMovieTypes { get; set; }
    }
}

VDOEasy/Models/MemberModalViewModel.cs
namespace VDOEasy.Models
{
    public class MemberModalViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime Birthdate { get; set; }
        public string Address { get; set; }
        public string IdcardNumber { get; set; }
    }
}

VDOEasy/Models/PrintRecieptModel.cs
namespace VDOEasy.Models
{
    public class PrintRecieptModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MemberType { get; set; }
        public string Address { get; set; }
    }
}

VDOEasy/Controllers/HomeController.cs
using Bogus;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;
using System.Linq;
using VDOEasy.ApplicationCore.Extensions;
using VDOEasy.ApplicationCore.Models;
using VDOEasy.Data.Models;
using VDOEasy.Data.Repositories.Interfaces;
using VDOEasy.Models;

namespace VDOEasy.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMemberRepository _memberRepository;
        private readonly IMemberTypeRepository _memberTypeRepository;
        private readonly IMovieTypeRepository _movieTypeRepository;
        private readonly IBranchRepository _branchRepository;

        public HomeController(ILogger<HomeController> logger, IMemberRepository memberRepository, IMemberTypeRepository memberTypeRepository, IMovieTypeRepository movieTypeRepository, IBranchRepository branchRepository)
        {
            _logger = logger;
            _memberRepository = memberRepository;
            _memberTypeRepository = memberTypeRepository;
            _movieTypeRepository = movieTypeRepository;
            _branchRepository = branchRepository;
        }

        public async Task<IActionResult> Index()
        {
            var branch = await _branchRepository.GetBranches();
            
            var model = new HomeViewModel
            {
                Branches = branch.Select(b => new SelectListItem { Value = b.Id.ToString(), Text = b.Name }).ToList(),
                MemberTypes = await _memberTypeRepository.GetMemberTypes(),
                MoviesTypes = await _movieTypeRepository.GetMovieTypes()
            };

            //Randomizer.Seed = new Random(8675309);

            //var members = new Faker<TrnMember>()
            //    .RuleFor(o => o.Firstname, f => f.Name.FirstName())
            //    .RuleFor(o => o.Lastname, f => f.Name.LastName())
            //    .RuleFor(o => o.Birthdate, f => f.Date.Past(50))
            //    .RuleFor(o => o.Address, f => f.Address.FullAddress())
            //    .RuleFor(o => o.IdcardNumber, f => f.Random.Number(100000000, 999999999).ToString())
            //    .RuleFor(o => o.MemberTypeId, f => f.Random.Number(1, 2))
            //    .Generate(10);
            //foreach (var member in members)
            //{
            //    await _memberRepository.AddMember(member);
            //}
            return View(model);
        }
        [HttpPost]
        public async Task<PartialViewResult> GetEditUserModal(int memberId)
        {
            var user = await _memberRepository.GetMemberById(memberId);
            var branch = await _branchRepository.GetBranches();

            var model = new HomeViewModel
            {
                Branches = branch.Select(b => new SelectListItem { Value = b.Id.ToString(), Text = b.Name }).ToList(),
                MemberTypes = await _memberTypeRepository.GetMemberTypes(),
                MoviesTypes = await _movieTypeRepository.GetMovieTypes(),
                Id = memberId,
                FirstName = user.Firstname,
                LastName = user.Lastname,
                Birthdate = user.Birthdate,
                Address = user.Address,
                IdcardNumber = user.IdcardNumber,
                MemberTypeId = user.MemberTypeId.Value,
                UserMovieTypes = user.MovieTypes.Select(m => m.Id).ToList(),
            };
            return PartialView("_EditMemberPartial", model);
        }
        public async Task<IActionResult> PrintReciept(int memberId)
        {
            var member = _memberRepository.GetMemberById(memberId).GetAwaiter().GetResult();
            var model = new PrintRecieptModel
            {
                Id = memberId,
                FirstName = member.Firstname,
                LastName = member.Lastname,
                MemberType = await _memberTypeRepository.GetMemberTypeById(member.MemberTypeId.Value),
                Address = member.Address,
            };
            return View(model);
        }
        public IActionResult DeleteUser(int memberId)
        {
            _memberRepository.DeleteMember(memberId);
            return Ok();
        }
        [HttpPost]
        public async Task<JsonResult> Search(int? memberId, string firstName, string lastName, DateTime? birthdate, DataTableOptionModel option)
        {
            var result = await _memberRepository.GetMembers(option, id: memberId, firstName: firstName, lastName: lastName, birthdate: birthdate);
            return result.ToJsonResult(option);
        }
        [HttpPost]
        public IActionResult AddMember(TrnMember member, int memberType, int[] movieType)
        {
            if (ModelState.IsValid)
            {
                member.MemberTypeId = memberType;
                _memberRepository.AddMember(member, movieType).GetAwaiter().GetResult();
                return RedirectToAction("Index");
            }
            
            return PartialView("_AddMemberPartial");
        }
        public async Task<IActionResult> UpdateMember(TrnMember member, int memberType, int[] movieType)
        {
            if (ModelState.IsValid)
            {
                member.MemberTypeId = memberType;
                await _memberRepository.UpdateMember(member);
                return RedirectToAction("Index");
            }

            return PartialView("_EditMemberPartial");
        }
        [HttpDelete]
        public async Task<IActionResult> DeleteMember(int memberId)
        {
            await _memberRepository.DeleteMember(memberId);
            return Ok();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VDOEasy/ViewComponents/LeftNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace VDOEasy.ViewComponents
{
    public class LeftNavigationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

VDOEasy/ViewComponents/TopNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace VDOEasy.ViewComponents
{
    public class TopNavigationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

VDOEasy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model VDOEasy.Models.HomeViewModel
@* <div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div> *@
<style>
    h6{
        margin-bottom: 0;
    }
</style>
<div class="row align-items-center ibox-content" style="row-gap:1rem;">
    <div class="card">
        <div class="row align-items-center card-body" style="row-gap:1rem;">
            <div class="col-md-6 col-sm-12">
                <div class="d-flex flex-column" style="gap:1rem;">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-sm-3 col-12 p-0">
                            <h6 class="text-sm-end">Id</h6>
                        </div>
                        <div class="col-sm-6 col-12">
                            <input type="text" class="form-control" id="textId"/>
                        </div>
                    </div>
                    <div class="row align-items-center justify-content-center">
                        <div class="col-sm-3 col-12 p-0">
                            <h6 class="text-sm-end">First Name</h6>
                        </div>
                        <div class="col-sm-6 col-12">
                            <input type="text" class="form-control" id="textFirstName" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-sm-12">
                <div class="d-flex flex-column" style="gap: 1rem;">
                    <div class="row align-items-center justify-content-md-start justify-content-center align-items-center">
                        <div class="col-sm-2 col-12 p-0">
                            <h6 class="text-sm-end">Birthdate</h6>
                        </div>
                        <div class="col-sm-6 col-12">
                            <input class="form-control" type="date" id="textBirthdate" />
                        </div>
                    </div>
                    <div class="row align-items-center justify-content-md-start justify-content-center align-items-center">
                        <div class="col-sm-2 p-0">
                            <h6 class="text-sm-end">Last Name</h6>
                        </div>
                        <div class="col-sm-6">
                            <input class="form-control" type="text" id="textLastName" />
                        </div>
                        <div class="col-sm-3 col-4 mt-sm-0 mt-2">
                            <button type="button" class="btn btn-primary" id="search-button"><i class="bi bi-search"></i> Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body table-responsive">
            <div class="d-flex w-100 justify-content-end mb-2">
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addMemberModal"><i class="bi bi-plus-lg"></i> Add New</button>
            </div>
            <table id="member-table" class="table table-bordered table-hover table-striped" style="width:100%;" cellspacing="0"></table>
        </div>
    </div>
</div>
<partial name="_AddMemberPartial" model="Model"/>
<div id="edit-user">
</div>
@section Scripts{
    <script>
        let memberTable;
        $(document).ready(function () {
            memberTable = $('#member-table').DataTable({
                "processing": true,
                "serverSide": true,
                "searching": false,
                "scrollX": true,
                "pageLength": 10,
                "displayStart": 0,
                "bFilter": true,
                "bLengthChange": false,
                "ajax": {
                    url: '@Url.Action("Search")',
                    type: "POST",
                    data: (opt) => {
                        return {
                            memberId: `${$('#textId').val()}`,
                            firstName: `${$('#textFirstName').val()}`,
                            lastName: `${$('#textLastName').val()}`,
                            birthdate: `${$('#textDepartment').val()}`,
                            option: opt
                        };
                    },
                },
                "columns": [
                    { title: "Id", data: "id" },
                    { title: "First Name", data: "firstname" },
                    { title: "Last Name", data: "lastname" },
                    { title: "Birthdate", data: "birthdate" },
                    { title: "Address", data: "address" },
                    { title: "Action", data: "id", render: renderActionButtons }
                ]
            });
            $("#search-button").click(() => {
                memberTable.ajax.reload();
            });
        });
        function renderActionButtons(data, type, row) {
            return `<div class="d-flex justify-content-center" style="gap:.5rem">
                        <button class="btn btn-primary" onclick="editMember('${data}')"> <i class="bi bi-pen-fill"></i></button>
                        <button class="btn btn-outline-success" onclick="printReciept('${data}')"><i class="bi bi-file-earmark-text"></i></button>
                        <button class="btn btn-danger" onclick="deleteMember('${data}')"><i class="bi bi-trash-fill"></i></button>
                    </div>`;
        }
        function editMember(memberId) {
            console.log("edit btn")
            $.ajax({
                url: '@Url.Action("GetEditUserModal")',
                type: 'POST',
                data: { memberId: memberId },
                success: (result) => {
                    $("#edit-user").html(result);
                    $("#editModalCenter").modal("show")
                },
                error: (data) => {
                    console.log(data);
                }
            });
        }
        function deleteMember(memberId) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    console.log(memberId)
                    $.ajax({
                        url: '@Url.Action("DeleteMember")',
                        type: 'DELETE',
                        data: { memberId: memberId },
                        success: () => {
                            memberTable.ajax.reload();
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                            });
                        }
                    });
                }
            });
        }
        function printReciept(memberId) {
            window.open(`/Home/PrintReciept?memberId=${memberId}`, "_blank");
        }
    </script>

    <script>
    //     $(document).ready(() => {
    //         $("#addMemberForm").validate({
    //             rules: {
    //                 textFirstname: { required: true, maxlength: 100 },
    //                 textLastname: { required: true, maxlength: 100 },
    //                 textAddress: { required: true, maxlength: 225 },
    //                 birthdate: { required: true }
    //             }
    //         })
    //         $("#saveChangesBtn").click(function () {
    //             // if ($("#addMemberForm").valid()) {
    //             //     console.log("Valid");
    //             // }
    //         });
    //     })
    // </script>
}

VDOEasy/Views/Home/PrintReciept.cshtml
@using System.Text.RegularExpressions
@model VDOEasy.Models.PrintRecieptModel
@{
    Layout = null;
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<style>
    body {
        font-family: Arial, sans-serif;
    }

    .receipt {
        width: 600px;
        border: 1px solid black;
        padding: 20px;
        margin: auto;
    }

    .header {
        text-align: center;
        margin-bottom: 20px;
    }

    .details {
        margin-bottom: 20px;
    }

        .details div {
            margin-bottom: 5px;
        }

    .table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

        .table, .table th, .table td {
            border: 1px solid black;
        }

            .table th, .table td {
                padding: 10px;
                text-align: center;
            }

    .signature {
        display: flex;
        justify-content: space-between;
    }
</style>
<div class="receipt">
    <div class="header">
        <h1>ใบเสร็จรับเงิน</h1>
        <p>วันที่ [วันที่ออกใบเสร็จ]</p>
    </div>
    <div class="details">
        <div class="d-flex gap-2">
            <div class="fw-bold">รหัสสมาชิก </div>
            <div>@Model.Id</div>
        </div>
        <div class="d-flex gap-2">
            <div class="fw-bold">ชื่อ</div>
            <div> @Model.FirstName @Model.LastName</div>
        </div>
        <div class="d-flex gap-2">
            <div class="fw-bold">ที่อยู่</div>
            <div>@Model.Address</div>
        </div>
        
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ลำดับ</th>
                <th>รายการ</th>
                <th>จำนวนเงิน</th>
            </tr>
        </thead>
        <tbody>
            @{
                var match = Regex.Match(Model.MemberType, @"(\d{3,4})");
                var result = match.Groups[0].Value;
            }
            <tr>
                <td>1</td>
                <td>ค่าสมัครสมาชิกประเภท @Model.MemberType</td>
                <td>@result</td>
            </tr>
            <tr>
                <td colspan="2">รวมเงิน</td>
                <td>@result</td>
            </tr>
        </tbody>
    </table>
    <div class="d-flex flex-column">
        <div>ลงชื่อ ................................. ผู้รับเงิน</div>
        <div>นายปองพล ขาวดี</div>
    </div>
</div>

VDOEasy/Views/Home/_AddMemberPartial.cshtml
@model VDOEasy.Models.HomeViewModel
@{
}
<div class="modal fade" id="addMemberModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <form asp-controller="Home" asp-action="AddMember" class="modal-content" method="post">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add Member</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row" id="addMemberForm" >
                    <div class="col-6">
                        <div class="d-flex flex-column" style="gap:1rem">
                            <div class="d-flex align-items-center gap-5">
                                <div class="row align-items-center">
                                    <label class="m-0 col-5">Branch:</label>
                                    <select asp-items="Model.Branches" class="form-select col">
                                    </select>
                                </div>
                                <div class="row align-items-center">
                                    <label class="m-0 col-3">Date:</label>
                                    <input class="col form-control" value="@DateTime.Today.ToShortDateString()" readonly />
                                </div>
                            </div>
                            <div class="d-flex align-items-center justify-content-between gap-3">
                                <div class="d-flex align-items-center gap-1">
                                    <label class="m-0" style="min-width: fit-content">First Name:</label>
                                    <input class="form-control" type="text" id="textFirstname" asp-for="FirstName"/>
                                    <span asp-validation-for="FirstName" class="text-danger"></span>
                                </div>
                                <div class="d-flex align-items-center gap-1">
                                    <label class="m-0" style="min-width: fit-content">Last Name:</label>
                                    <input class="form-control" type="text" id="textLastname" asp-for="LastName"/>
                                    <span asp-validation-for="LastName" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="row align-items-center">
                                <label class="m-0 col-2">ID Card:</label>
                                <input class="col form-control" type="number" asp-for="IdcardNumber" />
                                <span asp-validation-for="IdcardNumber" class="text-danger"></span>
                            </div>

                            <div class="row align-items-center">
                                <label class="m-0 col-2">Address:</label>
                                <textarea class="col form-control" id="textAddress" asp-for="Address"></textarea>
                                <span asp-validation-for="Address" class="text-danger"></span>
                            </div>

                            <div class="row align-items-center">
                                <label class="m-0 col-2">Birthdate:</label>
                                <input class="col form-control" type="date" id="birthdate" required asp-for="Birthdate"/>
                                <span asp-validation-for="Birthdate" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="d-flex flex-column ps-2" style="gap:1rem">
                            <div class="row align-items-center text-nowrap">
                                <label class="m-0 col-2">Member Type:</label>
                                @foreach(var item in Model.MemberTypes)
                                {
                                    <div class="form-check">
                                        <input type="radio" id="@item.Name" name="memberType" value="@item.Id" class="form-check-input" required />
                                        <label for="test1" class="form-check-label">@item.Name</label>
                                    </div>
                                }
                            </div>

                            <div class="row align-items-center text-nowrap">
                                <label class="m-0 col-2">Favourtie Genre:</label>
                                @foreach (var item in Model.MoviesTypes)
                                {
                                    <div class="form-check">
                                        <input type="checkbox" id="@item.Name" name="movieType" value="@item.Id" class="form-check-input" required />
                                        <label for="test1" class="form-check-label">@item.Name</label>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="saveChangesBtn">Save changes</button>
            </div>
        </form>
    </div>
</div>

VDOEasy/Views/Shared/Components/TopNavigation/Default.cshtml
@{
}
<div class="page-heading">
    <h3>@ViewBag.Title</h3>
</div>

VDOEasy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VDOEasy</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/lib/mazer/css/mazer.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/mazer/css/mazer-dark.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/mazer/css/iconly.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VDOEasy.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/DataTables/datatables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/sweetalert/sweetalert2.min.css" asp-append-version="true" />
</head>
<body>
    <div id="app">
        <vc:left-navigation></vc:left-navigation>
        <div id="main">
            <main role="main" class="pb-3">
                <header class="mb-3">
                    <a href="#" class="burger-btn d-block d-xl-none">
                        <i class="bi bi-justify fs-3"></i>
                    </a>
                </header>
                <vc:top-navigation></vc:top-navigation>
                @RenderBody()
            </main>
        </div>
    </div>
    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/mazer/js/mazer.js"></script>
    <script src="~/lib/mazer/js/dark.js"></script>
    <script src="~/lib/DataTables/datatables.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert2.min.js"></script>
    @* <script src="~/lib/mazer/js/sidebar.js"></script> *@
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>